services:
  next-app:
    container_name: browniemaar
    build:
      context: ./
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3700:3700    
    environment:
      - PORT=3700
    networks:
      - default

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  default:
    name: nginx_proxy
    external: true
